<?php
/**
 * Created by PhpStorm.
 * User: amin__000
 * Date: 10/18/2017
 * Time: 10:11 AM
 */

namespace amintado\options\widgets;


use yii\base\Widget;

class settingsWidget extends Widget
{

    public function init()
    {
        //parent::init(); // TODO: Change the autogenerated stub
        echo $this->render('@vendor/amintado/yii2-option/views/widgets/settings.php');
    }
}